
let wordPool = [
  {'word': 'creeper',
  'used': false,
  'id':0},
  {'word': 'biome',
  'used': false,
  'id':1},
  {'word': 'enderman',
  'used': false,
  'id':2},
  {'word': 'nether',
  'used': false,
  'id':3},
  {'word': 'pickaxe',
  'used': false,
  'id':4},
  {'word': 'redstone',
  'used': false,
  'id':5},
  {'word': 'steve',
  'used': false,
  'id':6},
  {'word': 'mojang',
  'used': false,
  'id':7},
  {'word': 'redstone',
  'used': false,
  'id':8},
  {'word': 'bedrock',
  'used': false,
  'id':9},
  {'word': 'diamond',
  'used': false,
  'id':10},
  {'word': 'dungeon',
  'used': false,
  'id':11},
  {'word': 'ingot',
  'used': false,
  'id':12},
  {'word': 'lava',
  'used': false,
  'id':13},
  {'word': 'mob',
  'used': false,
  'id':14},
  {'word': 'obsidian',
  'used': false,
  'id':15},
  {'word': 'portal',
  'used': false,
  'id':16},
  {'word': 'pigman',
  'used': false,
  'id':17},
  {'word': 'zombie',
  'used': false,
  'id':18},
]


module.exports = wordPool
